"use client";
import { useState, type FormEvent } from "react";

const fields = "h-12 rounded-xl border border-navy/15 bg-white px-4 text-sm outline-none focus:border-teal focus:ring-2 focus:ring-teal/20";
export default function OrganizationInquiryForm() {
  const [status, setStatus] = useState<"idle"|"sending"|"sent"|"error">("idle");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if(status==="sending") return; setStatus("sending"); const form=event.currentTarget; const data=new FormData(form); const params=new URLSearchParams(location.search); const response=await fetch("/api/organization-inquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationName:data.get("organizationName"),organizationType:data.get("organizationType"),contactName:data.get("contactName"),email:data.get("email"),phone:data.get("phone"),programInterests:data.getAll("programInterests"),estimatedParticipants:data.get("estimatedParticipants"),message:data.get("message"),privacyAgreed:data.get("privacyAgreed")==="on",utmSource:params.get("utm_source"),utmMedium:params.get("utm_medium"),utmCampaign:params.get("utm_campaign"),utmContent:params.get("utm_content")})}); setStatus(response.ok?"sent":"error"); if(response.ok) form.reset(); }
  if(status==="sent") return <div className="rounded-3xl bg-white p-8 text-center"><h3 className="text-2xl font-black text-navy">문의가 접수되었습니다</h3><p className="mt-3 text-navy/65">내용을 확인한 뒤 영업일 기준 1일 이내 연락드리겠습니다.</p></div>;
  return <form onSubmit={submit} className="grid gap-4 rounded-3xl bg-cream p-6 text-left sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><input className={fields} name="organizationName" required maxLength={160} placeholder="기관·교회·학교명"/><select className={fields} name="organizationType" required defaultValue=""><option value="" disabled>기관 유형</option><option value="church">교회</option><option value="christian_university">기독교 대학</option><option value="university">일반 대학</option><option value="organization">기관·단체</option><option value="other">기타</option></select><input className={fields} name="contactName" required maxLength={60} placeholder="담당자 이름"/><input className={fields} name="phone" required inputMode="tel" placeholder="휴대전화"/><input className={fields} name="email" required type="email" placeholder="이메일"/><input className={fields} name="estimatedParticipants" type="number" min="1" max="10000" placeholder="예상 참여 인원(선택)"/></div><fieldset><legend className="mb-3 text-sm font-bold text-navy">관심 프로그램(복수 선택)</legend><div className="grid gap-2 sm:grid-cols-2">{[["lecture","진로 특강"],["workshop","Living by Design 워크숍"],["group_assessment","단체 Career Direct 평가"],["consulting","개인·소그룹 컨설팅"]].map(([v,l])=><label key={v} className="flex gap-2 text-sm"><input type="checkbox" name="programInterests" value={v}/>{l}</label>)}</div></fieldset><textarea className="min-h-32 rounded-xl border border-navy/15 bg-white p-4 text-sm outline-none focus:border-teal" name="message" maxLength={1000} placeholder="목적, 희망 일정 등 문의 내용을 적어주세요(선택)"/><label className="flex items-start gap-2 text-xs leading-5"><input className="mt-1" type="checkbox" name="privacyAgreed" required/><span><b>(필수)</b> 기관 문의 처리와 회신을 위한 개인정보 수집·이용에 동의합니다. <a href="/privacy" className="text-teal underline">내용 보기</a></span></label>{status==="error"?<p role="alert" className="text-sm font-bold text-red-600">서버에서 접수하지 못했습니다. 입력 내용을 확인하고 잠시 후 다시 시도해주세요.</p>:null}<button disabled={status==="sending"} className="h-13 rounded-full bg-navy px-6 font-bold text-white disabled:opacity-50">{status==="sending"?"접수 중...":"기관 프로그램 문의하기"}</button></form>;
}
